# Generated by Django 4.1 on 2022-10-22 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='casts_scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='casts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.TextField()),
                ('wristwidth', models.DecimalField(decimal_places=2, max_digits=90000)),
                ('wristhight', models.DecimalField(decimal_places=2, max_digits=90000)),
                ('clearence', models.DecimalField(decimal_places=2, max_digits=90000)),
                ('ABsection', models.DecimalField(decimal_places=2, max_digits=90000)),
                ('Bwidth', models.DecimalField(decimal_places=2, max_digits=90000)),
                ('Bhight', models.DecimalField(decimal_places=2, max_digits=90000)),
                ('castthinkniss', models.DecimalField(decimal_places=2, max_digits=90000)),
                ('BCsection', models.DecimalField(decimal_places=2, max_digits=90000)),
                ('Cheight', models.DecimalField(decimal_places=2, max_digits=90000)),
                ('Cwidth', models.DecimalField(decimal_places=2, max_digits=90000)),
                ('circulediameter', models.DecimalField(decimal_places=2, max_digits=90000)),
                ('leftpump', models.DecimalField(decimal_places=2, max_digits=90000)),
                ('handtip', models.DecimalField(decimal_places=2, max_digits=90000)),
                ('rightpump', models.DecimalField(decimal_places=2, max_digits=90000)),
                ('midhandthikness', models.DecimalField(decimal_places=2, max_digits=90000)),
                ('palmlength', models.DecimalField(decimal_places=2, max_digits=90000)),
                ('palmwidth', models.DecimalField(decimal_places=2, max_digits=90000)),
                ('thumbmusile', models.DecimalField(decimal_places=2, max_digits=90000)),
                ('pattrebdensity', models.DecimalField(decimal_places=2, default=5, max_digits=90000)),
                ('patternlength', models.DecimalField(decimal_places=2, default=5, max_digits=90000)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
