# Generated by Django 4.1 on 2022-10-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CastsTypes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casts_scan',
            name='patientname',
            field=models.TextField(default='john doe'),
        ),
        migrations.AlterField(
            model_name='casts',
            name='patientname',
            field=models.TextField(default='john doe'),
        ),
    ]
